### ISSUE TITLE
Error when trying to like loads of media's from one hashtag

### ISSUE THREAD

**Issue by hendrikbgr** [hendrikbgr/Instagram-Selenium-Bot#6]
**Describe the bug**
When I tried to like loads of media's from one hashtag I got an error which crashes the script.

**To Reproduce**
Set the max like limit to something hight like 200. After some time the script will run out of media because of the lazy loading of instagram. 

1. Start the script like usual
2. See error the following error after some time:
'...'
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
image already liked
trying to like image...
liked images: 6
trying to like image...
liked images: 7
trying to like image...
liked images: 8
trying to like image...
liked images: 9
trying to like image...
liked images: 10
trying to like image...
liked images: 11
Traceback (most recent call last):
  File "bot.py", line 80, in <module>
    watch_all_stories_close = webdriver.find_element_by_xpath("/html/body/div[1]/section/div/div/section/div[2]/button[3]/div/span")
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div[1]/section/div/div/section/div[2]/button[3]/div/span

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 108, in <module>
    '/html/body/div[4]/div[1]/div/div/a[2]')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div[4]/div[1]/div/div/a[2]

**Expected behaviour**
It is supposed to continue liking the media's

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [OSX]
 - Version [0.1.3]

**Additional context**
To fix this, the page needs to be scrolled down for a while when a new hashtag is loaded. This will force the lazy loading to load more media for the script to like

**Comment by hendrikbgr** [comment]
Can not reproduce. Instagram now loads images in a different way then before.
